defmodule PlasmaSiteWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :plasma_site

  # The session is signed and encrypted in an HTTP-only cookie so the browser
  # application cannot read the OpenRouter credential stored after sign-in.
  @session_options [
    store: :cookie,
    key: "_plasma_site_key",
    signing_salt: "K5ag6OX2",
    encryption_salt: "cP8HkcDOlzCFf4jN",
    http_only: true,
    secure: Application.compile_env(:plasma_site, :secure_cookies, false),
    same_site: "Lax"
  ]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :plasma_site,
    gzip: not code_reloading?,
    only: PlasmaSiteWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug PlasmaSiteWeb.Router
end
